#!/usr/bin/perl
#################################################################
$outputString = "";
$sourceFile = "/config/redirect.config";
open (IN, $sourceFile);
while (<IN>)
{
    chomp;
    my $line = $_;
    my ($sourceDomain, $destDomain) = split("&&", $line);
    $outputString .= &createConfig($sourceDomain, $destDomain) . "\n#######################################\n";
}
close (IN);
open (OUT, ">/var/www/html/.htaccess");
print OUT "RewriteEngine On\n";
print OUT "############################################\n";
print OUT $outputString;
close (OUT);
#################################################################
#################################################################
#################################################################
sub createConfig
{
    my ($sourceDomain, $destDomain) = @_;
    my @srcPts = split('\.', $sourceDomain);
    # my $outString = "<IfModule mod_rewrite.c>\n";
    #####
    $sourceDomainORIG = $sourceDomain;
    $sourceDomain =~ s/\./\\\./g;
    #####

    # $outString .=   "  RewriteEngine On\n";
    my $outString =   "RewriteCond %{HTTP_HOST} ^$sourceDomain\$";
    if (($srcPts[0] ne "www") && ("www." . $sourceDomainORIG ne $destDomain))
    {
        $outString .=   "  [OR]\n";
        $outString .=   "RewriteCond %{HTTP_HOST} ^www\.$sourceDomain\$\n";
    }
    else 
    {
        $outString .= "\n";
    }
    $outString .=   "RewriteRule ^(.*)\$ https://$destDomain/\$1 [R=301,L]\n";
    # $outString .=   "</IfModule>\n";
    return $outString;
}
